leavemanager/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
    path("profile/", views.ProfilePage.as_view(), name = "profile"),
    
]

leavemanager/leavemanager/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

admin.site.site_header = "Leave Manager Admin"
admin.site.site_title = "Leave Manager Admin Portal"
admin.site.index_title = "Welcome to Leave Manager Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('', views.HomePage.as_view(), name ="home"),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('error/', views.ErrorPage.as_view(), name="error"),
    path('lrequests/', include('lrequests.urls', namespace = 'leaverequest')),
]

leavemanager/lrequests/urls.py
from django.urls import path, include
from . import views

app_name='lrequests'

urlpatterns = [
    path('lrequests/',views.leaveRequest, name = 'request'),
    path('status/', views.get_data, name = 'status'),
    path('calendar/', views.calendar_data, name = 'calendar')
 

    
]

leavemanager/lrequests/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models import F

CHOICES = (('Earned Leave','Earned Leave'),('Casual Leave','Casual Leave'),('Sick Leave','Sick Leave'),('Paid Leave','Paid Leave'))
STATUS_CHOICES = (('0', 'Rejected'),('1', 'Accepted'),)
MANAGER_CHOICES = (('0001_manager', '0001_manager'),('0002_manager', '0002_manager'))
DEPARTMENT_CHOICES = (('Python','Python'), ('Javascripr','Javascript'))
DESIGNATION_CHOICES = (('Developer', 'Developer'), ('Designer','Designer'))

class Leave(models.Model):

    employee_ID = models.CharField(max_length = 20)
    name = models.CharField(max_length = 50)
    user = models.ForeignKey(User, on_delete = models.CASCADE, null =True)
    department = models.CharField(max_length = 50, choices = DEPARTMENT_CHOICES)
    designation = models.CharField(max_length = 50, choices = DESIGNATION_CHOICES)
    type_of_leave = models.CharField(max_length = 15, choices = CHOICES)
    from_date = models.DateField()
    to_date = models.DateField()
    reporting_manager = models.CharField(max_length = 50, choices = MANAGER_CHOICES)
    reason = models.CharField(max_length= 180)
    status = models.CharField(max_length = 15, choices = STATUS_CHOICES)
    reason_reject = models.CharField(('reason for rejection'),max_length=50, default = '-') #blank=True)
    created = models.DateField(auto_now_add=True, editable=False, null=False, blank=False)
    last_modified = models.DateField(auto_now=True, editable=False, null=False, blank=False)


    def __str__(self):
        return self.name

    @property
    def date_diff(self):
        return (self.to_date - self.from_date).days + 1
         

    class Meta:
        verbose_name = "Leaves Applied"
        verbose_name_plural = "Leaves Applied"
    
    def save(self, *args, **kwargs):
        super(Leave, self).save()
        if self.status == '1':
            if self.type_of_leave == 'Earned Leave':
                    history = History.objects.filter(employee_ID=self.employee_ID).update(
                earned_leave = F('earned_leave') - self.date_diff,  
            )
            elif self.type_of_leave == 'Casual Leave':
                    history = History.objects.filter(employee_ID=self.employee_ID).update(
                casual_leave = F('casual_leave') - self.date_diff,  
            )
            elif self.type_of_leave == 'Sick Leave':
                    history = History.objects.filter(employee_ID=self.employee_ID).update(
                sick_leave = F('sick_leave') - self.date_diff,  
            )
            elif self.type_of_leave == 'Paid Leave':
                    history = History.objects.filter(employee_ID=self.employee_ID).update(
                paid_leave = F('paid_leave') - self.date_diff,  
            )


   


class History(models.Model):

    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    employee_ID = models.CharField(max_length = 20)
    earned_leave = models.IntegerField()
    casual_leave = models.IntegerField()
    sick_leave = models.IntegerField()
    paid_leave =models.IntegerField()

    class Meta:
        verbose_name = "Employee's Leaves Eligibility"
        verbose_name_plural = "Employee's Leaves Eligibility"

class Calendar(models.Model):

    date = models.DateField()
    occasion = models.CharField(max_length = 20)

leavemanager/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Leave Manager</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js">
    </script>
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css"> 
    <!-- Script -->
    <script src="http://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>

    <script>

    $(document).ready(function() {
        $('.datepicker').datepicker(
          {
            minDate : 0,
            beforeShowDay : $.datepicker.noWeekends
          }
        );
    });
    
    </script>
    {% comment %} <script>
      var array = [
    {% for x in holidays %}
        {{x.dates}}
    {% endfor  %} 
]

$('datepicker').datepicker({
    beforeShowDay: function(date){
        var string = jQuery.datepicker.formatDate('yy-mm-dd', date);
        return array.indexOf(string) != -1 ? [false] : $.datepicker.noWeekends(date);
    }
});
    </script> {% endcomment %}

    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'leavemanager/css/master.css'%}">
    
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
  </head>


  <body>

        <nav class="navbar  mynav" role="navigation" id="navbar">
    			<div class="container">
            <a class="navbar-brand mynav"> LEAVE-MANAGER.com </a>
            
    					<ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                      <li><a class="btn btn-simple" href="{% url 'home' %}">Home</a></li>
                      {% if user.is_superuser %}
                      <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
                      {% elif user.is_staff%}
                      <li><a href="{% url 'calendar' %}" class="btn btn-simple">Holiday Calendar</a></li>
                      <li><a href="{% url 'accounts:profile' %}" class="btn btn-simple">Profile</a></li>
                      <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
                      {% else %}
                      <li><a href="{% url 'lrequests:status' %}" class="btn btn-simple">Activity</a></li>
                      <li><a href="{% url 'lrequests:request' %}"class="btn btn-simple">Make a request</a></li>
                      <li><a href="{% url 'lrequests:calendar' %}" class="btn btn-simple">Holiday Calendar</a></li>
                      <li><a href="{% url 'accounts:profile' %}" class="btn btn-simple">Profile</a></li>
                      <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
                      

                      {% endif %}
                      

                {% else %}
                      <li><a class="btn btn-simple" href="{% url 'home' %}">Home</a></li>
    						      <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      {% comment %} <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li> {% endcomment %}
    						{% endif %}
    					</ul>
    			</div>
        </nav>
        
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>
  </body>
  
  <script src="{% static "leavemanager/js/master.js"%}" type="text/javascript" ></script>
</html>

leavemanager/templates/calendar.html
{% extends "base.html" %}
{% block content %}
<div class = 'container'>
  <h2> Office Holidays </h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Date</th>
        <th scope ="col">Month</th>
        <th scope="col">Day</th>
        <th scope ="col">Occasion</th>
      </tr>
    </thead>
    {% for x in holidays  %}
    <tr>
        <th scope="row">{{x.date|date:"d"}}</th>
        <td>{{x.date|date:"F"}}</td>
        <td>{{x.date|date:"l"}}</td>
        <td>{{x.occasion}}</td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock content %}

leavemanager/templates/change_password.html
{% extends "base.html" %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{ pc_form }}
    <button type="submit">Save changes</button>
  </form>

{% endblock content %}

leavemanager/templates/error.html
{% extends "base.html" %}
{% block content %}

<div class="alert alert-danger">
    <strong>Error!</strong> 'From' date is greater than 'To' date.
  </div>

{% endblock content %}

leavemanager/templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to Leave Manager!</h1>
    <h2>Login to get started!</h2>

{% endblock %}

leavemanager/templates/profile.html
{% extends "base.html" %}
{% block content %}
    <div class="container">

        <form role="form", method="POST">
            <h2>My Profile</h2>
                <table class="table">
                    <tr>
                        <td>
                            <h3>Name : {{user.first_name}} {{user.last_name}}</h3>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <h3>User ID : {{user.username}}</h3>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <h3>Email : {{user.email}}</h3>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <h3>
                                {% if perms.lrequests.change_leave%}
                                Check if you need to approve any leaves, <a href="http://127.0.0.1:8000/admin/lrequests/leave/">here</a>
                                {% else %}
                                
                                {% endif %}
                                
                            </h3>
                        </td>
                    </tr>
                </table>
        </form>

    </div>

{% endblock content %}

leavemanager/templates/request_form.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h3>  Fill out the form please! </h3>
    <h4>
        <form action="." role="form", method="POST">
            {% csrf_token %}
            
            {{ form.as_p }}
            
            <button type = "submit">Submit</button>
        </form>
    </h4>
</div>
{% endblock %}

leavemanager/templates/status.html
{% extends "base.html" %}


{% block content %}

<h3>{{user.first_name}} {{user.last_name}}'s Leave activity : </h3> <br>
    <table class = 'table'>
        <tr>
            <th>ID</th>
            <th>Date Applied</th>
            <th>Accepted On</th>
            <th>From Date</th>
            <th>To Date</th>
            <th>Number of Days</th>
            <th>Type of Leave</th>
            
        </tr>
        <tr>
                {% for x in data %}
                    {% if x.status == '1' %}
                    <tr>
                        <th scope = 'row'>  {{x.id}}  </th>
                        <td>  {{x.created}}  </td>
                        <td>  {{x.last_modified}}  </td>
                        <td>  {{x.from_date}}  </td>
                        <td>  {{x.to_date}}  </td>
                        <td>  {{x.date_diff}}  </td>
                        <td>  {{x.type_of_leave}}  </td>
                    {% else %}
                    {% endif %} 
                </tr>                      
                {% endfor %}
    
        </tr>
    </table>
    <br>
<h3>{{user.first_name}} {{user.last_name}}'s Leave Eligibility</h3>
    <table class = 'table'>
        <tr>
            <th>Earned Leave's left</th>
            <th>Casual Leave's left</th>
            <th>Sick Leave's left</th>
            <th>Paid Leave's left</th>
        </tr>
        <tr>
            {% for y in count  %}
            <td>{{y.earned_leave}}</td>
            <td>{{y.casual_leave}}</td>
            <td>{{y.sick_leave}}</td>
            <td>{{y.paid_leave}}</td>
            
            {% endfor %}
        </tr>
</table>
{% endblock content %}

leavemanager/templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>
    {% if user.is_authenticated %}
    {% if user.is_superuser %}
    Welcome !!
    Head to the admin page, <a href="http://127.0.0.1:8000/admin/">here</a>
    {% else %}
    <p>Welcome, {{ user.first_name }} {{ user.last_name }}. Thanks for logging in.</p>
    <h2><a href="{% url 'lrequests:request' %}">Make a request!</a></h2>
    {% endif %}
    
    {% else %}
    <p>Welcome, new user. Please log in.</p>

    {% endif %}
  </h1>
  
  
  {% comment %} <p></p>
  <p></p>
  <p></p>
  <p></p>
  <h2>Your left over leaves:</h2>
  <h3>
    <ul>
      <li>Earned Leave : 05</li><p></p>
      <li>Casual Leave : 06</li><p></p>
      <li>Sick Leave   : 12</li><p></p>
      <li>Paid Leave   : 08</li><p></p>
    </ul>
</h3>  {% endcomment %}
</div>




{% endblock %}

leavemanager/templates/thanks.html
{% extends "base.html" %}
{% block content %}
{% comment %} <h1>Hope we won't see you soon enough.</h1> {% endcomment %}
<p> <h1>Thanks!</h1> </p>

{% endblock %}